;;; File to be loaded when I want to program
;;; Contrary to the name, should not be loaded as 'init.el'
(setq cursor-blink-mode 0)
;;; CUSTOM SETUP
(defvar wget-fetch-filename nil
  "For communicating between the function 'wget-fetch' and its sentinel.")
(defun wget-fetch (link)
  "Download LINK using wget, into the 'user-emacs-directory'."
  (setq wget-fetch-filename (file-name-nondirectory link))
  (if (file-exists-p (concat user-emacs-directory wget-fetch-filename))
      (let (
            (inhibit-message t)
            )
        (message (concat wget-fetch-filename " is already downloaded, so not downloading!"))
        )
    (let* (
           (prev-dir default-directory)
           )
      (setq default-directory user-emacs-directory)
      (unwind-protect
          (set-process-sentinel
           (start-process "WGET-FETCH" "*WGET-FETCH*" "wget" "-q" link)
           (lambda (proc happen)
             (when (string-match "finished" happen)
               (message (concat wget-fetch-filename " has been downloaded!"))
               )
             )
           )
        (setq default-directory prev-dir)
        )
      )
    )
  )

;;; PACKAGE SETUP
(use-package company
  :ensure t
  :hook (prog-mode . company-mode))

(use-package lsp-mode
  :ensure t)

(use-package yasnippet
  :ensure t
  :config
  (yas-global-mode 1))
(use-package yasnippet-snippets
  :ensure t)

(use-package magit
  :ensure t)
(use-package forge
  :ensure t)

;;; DM setup
(wget-fetch "raw.githubusercontent.com/Djiq/opendream-mode/refs/heads/master/opendream-mode.el")
(load-file (concat user-emacs-directory "opendream-mode.el"))
(wget-fetch "https://github.com/SpaceManiac/SpacemanDMM/releases/download/suite-1.10/dm-langserver")
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("~/.emacs.d/dm-langserver"))
  :major-modes '(opendream-mode)
  :server-id 'dreammaker-server))

(use-package kaolin-themes
  :ensure t
  :config
  (load-theme 'kaolin-temple t))

(global-hl-line-mode 1)
(custom-set-faces
 '(hl-line ((t (:background "#5c5c5c")))))

;;; C setup
;;; User-functions
(defvar compile-and-run-pass-bucket nil
  "Intermezzo var to pass directory that 'compile-c-file' is running in to 'compile-and-run-hook'.")
(defun compile-c-file ()
  "Compiles the current C file, and runs it."
  (interactive)
  (if (or
       (eq major-mode 'c-mode)
       (eq major-mode 'c-ts-mode))
      (let (
            (cur-buf-name (buffer-name (current-buffer)))
            )
        (save-buffer)
        (setq compile-and-run-pass-bucket (list (file-name-directory (buffer-file-name (current-buffer))) cur-buf-name))
        (compile (concat "gcc -O0 -g -o " (file-name-sans-extension cur-buf-name) " " cur-buf-name))
        )
    (message "This is not a C buffer!")
      )
  )

(defun compile-and-run-hook (comp-buf out-str)
  "Uses OUT-STR from COMP-BUF to run the executable generated by 'compile-c-file'."
  (when (and
         (string-match "finished" out-str)
         (not (string-match "error" out-str)))
    (let (
          (src-name (nth 1 compile-and-run-pass-bucket))
          (exec-dir (car compile-and-run-pass-bucket))
          )
      (select-window (get-buffer-window comp-buf))
      (unless (string-match "*shell*" (buffer-name (window-buffer (next-window))))
          (split-window-below nil (get-buffer-window comp-buf))
          )
      (other-window 1)
      (shell)
      (goto-char (point-max))
      (insert (concat "cd " exec-dir))
      (comint-send-input)
      (accept-process-output (get-buffer-process (current-buffer)) 1 0 t)
      (goto-char (point-max))
      (insert (concat "./" (file-name-sans-extension src-name)))
      (goto-char (point-max))
      (comint-send-input)
      (select-window (get-buffer-window src-name))
      )
    )
  )
(add-hook 'compilation-finish-functions 'compile-and-run-hook)

;;; Keybind setup
(add-hook 'c-mode-hook
	  (lambda ()
	    (local-set-key (kbd "C-c -") 'compile-c-file)))
(add-hook 'c-ts-mode-hook
	  (lambda ()
	    (local-set-key (kbd "C-c -") 'compile-c-file)))
(global-set-key (kbd "C-c b") 'eval-buffer)
